modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "enchantrepair"
version = "${version}"
displayName = "Enchant & Repair"
authors = "orlouge"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
